# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

first = 1
second = 2
next_term = 0
max_term_value = 4000000
array = []
sum = 0

loop do

    if ( first > max_term_value )
        break
    end

    array.push(first)
    next_term = first + second
    first = second
    second = next_term

end

array.each do |num|
    print "#{num}, "
    if ( num % 2 == 0 )
        sum += num
    end
end

puts "\n\n"

puts "SUM OF EVEN => #{sum}"
